### ISSUE TITLE
DropinError

### ISSUE THREAD

**Issue by timscott** [kovndr/braintree-dropin-react#10]
I'm getting the following error after successfully making a payment. I'm following the example, pretty close.

```js
{
  name: "DropinError", 
  message: "options.selector or options.container must reference a valid DOM node.",
  _braintreeWebError: undefined
}
```

What could it be? A bug?

**Comment by kovndr** [comment]
I have tested this with braintree-web-drop-in(1.9.4) and not getting any error.
What are you doing after `handlePaymentMethod` ?

**Comment by timscott** [comment]
Thanks for the reply. I found the problem. In the callback after sending the payment details to my server, I was clearing the shopping cart (in redux) then navigating to the next page (`reactRouter.history.push`).

Clearing the shopping cart shopping was causing the component to needlessly re-render one more time. It seems this re-render immediately before pushing the route were causing some condition that `braintree-web-drop-in` cannot handle. I'm still not sure why, but clearing the cart after the navigation fixes it.
