### ISSUE TITLE
The handlePaymentMethod is not being called for PayPal integration

### ISSUE THREAD

**Issue by mattruma** [kovndr/braintree-dropin-react#12]
I have the following code:

<BraintreeDropIn
braintree={braintree}
authorizationToken={authorizationToken}
handlePaymentMethod={this.handlePaymentMethod}
paypal={{
flow: "vault",
singleUse: false
}}
/>

The handlePaymentMethod is called when credit cards are used, but not PayPal.

Am I doing something incorrectly?

**Comment by kovndr** [comment]
You have to configure PayPal in Control Panel.
