### ISSUE TITLE
Add button to delete a payment method

### ISSUE THREAD

**Issue by alexandrudanpop** [kovndr/braintree-dropin-react#13]
Would be nice to have the ability to select a payment method and have a button to delete it.

This would require an additional prop handleDeletePaymentMethod that is called with the paymentMethodToken. Then this paymentMethodToken can be used to call the  payment-method/delete API in the backend
https://developers.braintreepayments.com/reference/request/payment-method/delete/node

**Comment by kovndr** [comment]
This functionality is not the purpose of the project, its not closely related to the Drop-In UI.
