### ISSUE TITLE
`handlePaymentMethod` is never called.

### ISSUE THREAD

**Issue by luanfonceca** [kovndr/braintree-dropin-react#14]
Differently from the issue #12, in my case in both cases (Credit card and Paypal) the `handlePaymentMethod` is never called.

In both cases when i click on the "Submit Button" from my DropIn, it goes to disabled but nothing else happens, there are no logs on my browser devtools "log" and no requests on the "Network" tab.

Follows a gif: http://recordit.co/DjUPRX9v7g

My component declaration:
```jsx
<BraintreeDropIn
  braintree={braintree}
  paymentOptionPriority={['card', 'paypal']}
  paypal={{
    flow: 'vault',
    amount: customCredit || credit,
    currency: 'USD',
  }}
  authorizationToken={clientToken}
  handlePaymentMethod={this.handlePaymentMethod}
  onCreate={this.onCreate}
  onDestroyStart={this.onDestroyStart}
  onDestroyEnd={this.onDestroyEnd}
  onError={this.onError}
  renderSubmitButton={paymentButtonComponent}
  className={s.paymentWidget}
/>

```

My Button component:
```jsx
let paymentButtonComponent = ({onClick, isDisabled, text}) => {
  return (
    <Button color="primary" onClick={onClick} disabled={isDisabled} className={s.paymentButton}>
      {text}
    </Button>
  )
};

```

My `handlePayment` code:
```jsx

handlePaymentMethod(payload) {
  console.log('handlePaymentMethod()');
}
```

The `{clientToken}` come from my python api and its a Client token based on the logged user on my app.

**Comment by kovndr** [comment]
Sorry for the delayed response. I did success payment with card and paypal too with your options.
(braintree-web-drop-in 1.11.0, braintree 2.11.0)
