### ISSUE TITLE
Missing vaultManager configuration in braintree create params.

### ISSUE THREAD

**Issue by tri-dang** [kovndr/braintree-dropin-react#15]
I need to configure vaultManager to allow a customer to delete saved payment methods, document: https://braintree.github.io/braintree-web-drop-in/docs/current/module-braintree-web-drop-in.html#.create

**Comment by kovndr** [comment]
The new 0.1.1 version is out. Now you can use the options prop like this:
`options={{vaultManager: false}}`

**Comment by shan-du** [comment]
just curious, is there a reason why this issue is still open tho?

**Comment by kovndr** [comment]
No reason I just forgot to close.
