### ISSUE TITLE
Payload nonce doesn't get updated on authorizationToken state change

### ISSUE THREAD

**Issue by d30jeff** [kovndr/braintree-dropin-react#3]
When I submit a form for the second time, I'm getting the same payload as the one in the previous state.

On the first submission, I fetch the `clientToken` from the backend for the second time and set the `authorizationToken` state to the new token.

**Comment by kovndr** [comment]
Hello,
I can't reproduce this behavior with **braintree-web-drop-in** (1.9.2) and **braintree** (2.4.0)
