### ISSUE TITLE
'No valid payment method' Error

### ISSUE THREAD

**Issue by iamthuypham** [kovndr/braintree-dropin-react#7]
Hello!

I really like your library.

Just add this to your doc would save a little time: "Require at least one payment method (PayPal, PayPalCredit, etc.) in the component".
I have this error when I did not add any.

Also, in the example `ClientApp.js`, I believe this line:

`import BraintreeDropIn from "../index"`

should be:

`import BraintreeDropIn from "braintree-dropin-react"`

Thanks

**Comment by iamthuypham** [comment]
Oh, I researched a little deeper. The `card` payment method should display by default. But somehow, in my case, it does not show, instead, showing the `No valid payment method` error.

Did I miss anything in the configuration?

**Comment by kovndr** [comment]
Hello!
I can't see the problem. Maybe check the settings on the website.
